name: Typeset

on: push

jobs:
    typeset:
        name: Typeset
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Install dependencies
              run: cargo install --locked typst-cli@0.12.0
            - name: Check out
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            - name: Compile PDF
              run: typst compile main.typ main.pdf
            - name: Release
              uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
              with:
                  files: main.pdf
                  prerelease: true
                  make_latest: true
